Update imin.jsonld
imin-ltd/extension-namespace pull request #3
Opened 2021-07-05 11:51 UTC by Mortuie

Adding

- `imin:aggregatedActivity`
- `beta:presentAsSlots`

2021-07-05 11:53 UTC, Mortuie commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update https://ns.imin.co/ (needed for Firehose?)](https://trello.com/c/U1OqQWca/3304-update-https-nsiminco-needed-for-firehose)

2021-07-06 15:00 UTC, lukehesluke requested changes

2021-07-06 15:00 UTC, lukehesluke commented on imin.jsonld
> +      ],
This defines `aggregatedActivity` as a field on the `skos:Concept` object which has type `String`.

It looks like this is in fact a field on the `Place` object which is of type `skos:Concept`

So domainIncludes should be `schema:Place` and rangeIncludes should be `skos:Concept`.

Btw the way this was explained to me which I find very helpful is that a `Property` is a function that maps the "object" type to the "field" type.

i.e.

```
aggregatedActivity = (Place) => string
```

And so it's using "domain" and "range" in the same way they're used in functions in maths. The "domain" is the set of values the function can take and "range" is the set of values the function can output.

`Property`s are actually edges in a big directed graph where types are nodes. And therefore it's more like:

```
Place ----aggregatedActivity---> string
```

But in this language, they're modelling graph edges as functions like `f(fromNode) => toNode`

It's weird but I hope that makes sense

2021-07-06 15:00 UTC, lukehesluke commented on imin.jsonld
> +      "id": "beta:presentAsSlots",
Beta fields should be in the beta namespace (https://openactive.io/ns-beta/). This is not in there presently which means either:

* It's a mistake and it should be `imin:presentAsSlots`
* We are petitioning for OA to include it in the beta namespace? Though I see no issues there (https://github.com/openactive/ns-beta/issues?q=is%3Aissue+presentAsSlots)

So presumably this should be `imin:presentAsSlots`. Now of course it's in the Agg code as `beta:presentAsSlots` so I expect that needs changing also. I believe @civsiv knows more about this field. @civsiv?

2021-07-06 15:00 UTC, lukehesluke commented on imin.jsonld
> +      ],
It looks like we set this field in EventSeries objects. So, domain should be `pending:EventSeries`. `pending:` because it is not yet definitively in Schema.org. EventSeries has the same prefix here: https://openactive.io/ns/oa.jsonld

2021-07-08 10:01 UTC, lukehesluke approved these changes

2021-07-08 10:40 UTC, Mortuie commented on imin.jsonld
> +      "type": "Property",
why do these properties not have @id and @type

2021-07-08 10:40 UTC, Mortuie commented on imin.jsonld
> +      "@type": "Property",
whereas these do?

2021-07-08 11:02 UTC, lukehesluke approved these changes

2021-07-08 11:02 UTC, lukehesluke commented on imin.jsonld
> +        "imin:Level@type"
Oops

2021-07-08 11:06 UTC, merged

2021-07-08 11:49 UTC, Mortuie commented on imin.jsonld
> +      "@type": "imin:Level@type",
is this the desired result ?